name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --locked cargo-machete
      - run: cargo binstall --locked cargo-sort-derives
      
      # Checks
      - run: cargo +nightly fmt --check
      - run: cargo check
      - run: cargo clippy
      - run: cargo machete
      - run: cargo sort-derives --check

      # Tests
      - run: cargo test
